// TODO(contract-pipeline) — yours to write.
//
// Shape of the finished package:
//   src/schema.d.ts  GENERATED by openapi-typescript from ../../contracts/openapi.json — committed, never hand-edited
//   src/index.ts     a small factory: takes a baseUrl, returns an openapi-fetch client typed by `paths` from schema.d.ts
//
// Things to decide/look up:
//   - which openapi-typescript CLI flags you want (the input/output paths are the only mandatory ones)
//   - a "generate" script in this package.json that Taskfile's `codegen` task can call
//   - how web gets its baseUrl (env var, e.g. API_URL) — the client should not read env itself
export {};
